### ISSUE TITLE
cost_utils.CostDistribution Incorrect Attribute docstring

### ISSUE THREAD

**Issue by Kieran-Fishwick-TfN** [Transport-for-the-North/caf.toolkit#133]
the attributes outlined in the attribute docstring do not exist and are misleading as to how the class init works

**Comment by BenTaylor-TfN** [comment]
Could you vaguely outline what you'd like to see in the docs please? Current docs are here:
https://caftoolkit.readthedocs.io/en/v0.7.3/api/cost_utils.CostDistribution.html#cost_utils.CostDistribution
