### ISSUE TITLE
numpy 1.24

### ISSUE THREAD

**Issue by isaac-tfn** [Transport-for-the-North/caf.toolkit#19]
When importing caf.toolkit with numpy>=1.24.0, it returns "SystemError: initialization of _internal failed without raising an exception".
Everything works fine with numpy=1.23.5

**Comment by BenTaylor-TfN** [comment]
This appears to be an issue with numba, which doesn't yet support numpy 1.24, see below for updates:
https://github.com/numba/numba/issues/8464

We should probably pin our numpy version number for now and track this issue until it's solved.
