### ISSUE TITLE
ConfigBase Test Error

### ISSUE THREAD

**Issue by BenTaylor-TfN** [Transport-for-the-North/caf.toolkit#21]
Looks like there is an error being caused by the following class when running tests:

https://github.com/Transport-for-the-North/caf.toolkit/blob/8accd4dfa9b4226dcd211b6c7c23cd91bcf570b2/tests/test_config_base.py#L72

Error:
```
tests\test_config_base.py:71
  C:\Users\Sneezy\Desktop\GitHub\caf.toolkit\tests\test_config_base.py:71: PytestCollectionWarning: cannot collect te
st class 'TestSubClass' because it has a __init__ constructor (from: tests/test_config_base.py)
    @dataclasses.dataclass

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

Pytest is picking it up as the class has the word "Test" in it. Does this class just need renaming? @isaac-tfn

**Comment by isaac-tfn** [comment]
Yes I think so, I don't know how I didn't catch that when I was running tests on it

**Comment by BenTaylor-TfN** [comment]
I don't think it's a full error - the tests still pass. Just Pytest complaining that it found a test that it can't run.

Could you pick up when you get a little bit of time?

**Comment by isaac-tfn** [comment]
Sure no problem I should have time today

**Comment by BenTaylor-TfN** [comment]
@isaac-tfn I see you've created a fix for this. How close are we to solving this issue?

**Comment by isaac-tfn** [comment]
I think it's solved now, but after I did this it seemed like it had been fixed in another branch for another bug. I'll have another look now and get this closed either way.
