### ISSUE TITLE
Update Pydantic support to >=2.0.0

### ISSUE THREAD

**Issue by BenTaylor-TfN** [Transport-for-the-North/caf.toolkit#95]
Pydantic recently updated to 2.0.0, we should update to support the new version. Without this, `BaseConfig` classes will fall behind.

@AdilZ16 needs this for some work he is currently working on.

**Comment by wsp-mbuckley** [comment]
Is this a priority for this week or does it want to wait until the new year?

**Comment by BenTaylor-TfN** [comment]
It can wait until the new year!

**Comment by wsp-mbuckley** [comment]
Done in #98
